-- TO DELETE A DB, YOU NEED TO BE ON ANOTHER DB
PRINT 'USING MASTER DB...'
USE MASTER;
GO
-- DELETE THE TEMPDEVDB DATABASE IF IT EXISTS  
PRINT 'CHECKING IF ASSIGNMENT2 EXISTS...'
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='ASSIGNMENT2')
    -- DELETE DATABASE TEMPDEVDB
BEGIN
	PRINT 'ASSIGNMENT2 EXISTS AND WILL BE DELETED...'
	DROP DATABASE ASSIGNMENT2;
END;

BEGIN
	PRINT 'MKANDASAMY5 DOES NOT EXISTS AND WILL BE CREATED...'
	CREATE DATABASE ASSIGNMENT2;
END;
GO

USE ASSIGNMENT2;
PRINT 'USING MKANDASAMY5 DB...'
GO

-- CREATE USR_108601170_TB TABLE
PRINT 'CREATING USER_ACCOUNT TABLE...'
CREATE TABLE USER_ACCOUNT(
USERID INTEGER NOT NULL,
USERNAME VARCHAR(50) UNIQUE,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
PASSWORD VARCHAR(50),
EMAIL VARCHAR(50),
ISACTIVE BIT DEFAULT 0,
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (USERID));
GO

-- CREATE USR_108601170_TB TABLE
PRINT 'CREATING USER_QUSTN_LST TABLE...'
CREATE TABLE USER_QUSTN_LST(
QUESTIONID INTEGER NOT NULL,
QUESTION VARCHAR(150),
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (QUESTIONID));
GO


-- CREATE USR_108601170_QA_TB TABLE
-- Contains the security question and answer for the user
PRINT 'CREATING USER_QA_TB TABLE...'
CREATE TABLE USER_QA_TB(
ID INTEGER NOT NULL,
USERID INTEGER NOT NULL,
QUESTIONID  INTEGER NOT NULL,
ANSWER VARCHAR(50),
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (ID)
CONSTRAINT FK_USER_QA_TB_USER_ACCOUNT FOREIGN KEY (USERID)     
REFERENCES USER_ACCOUNT (USERID),     
CONSTRAINT FK_USER_QA_TB_USER_QUSTN_LST FOREIGN KEY (QUESTIONID)     
REFERENCES USER_QUSTN_LST (QUESTIONID)
);
GO

-- CREATE BANK_ACCOUNT TABLE
PRINT 'CREATING BANK_ACCOUNT TABLE...'
CREATE TABLE BANK_ACCOUNT(
ID INTEGER NOT NULL,
USERID INTEGER NOT NULL,
ACCOUNTID VARCHAR(150) NOT NULL,
ACCOUNTTYPE VARCHAR(10),
BALANCE INTEGER,
ISACTIVE BIT DEFAULT 0,
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (ID),
CONSTRAINT FK_BANK_ACCOUNT_USER_ACCOUNT FOREIGN KEY (USERID)     
REFERENCES USER_ACCOUNT (USERID)
);
GO

-- CREATE BANK_TRANSACTION TABLE
PRINT 'CREATING BANK_TRANSACTION TABLE...'
CREATE TABLE BANK_TRANSACTION(
ID INTEGER NOT NULL,
USERID INTEGER NOT NULL,
ACCOUNTID INTEGER NOT NULL,
TRANSACTIONTYPE VARCHAR(10),
AMOUNT INTEGER,
MEMODESCRIPTION VARCHAR(10),
CREATEDDATE DATETIME DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (ID),
CONSTRAINT FK_BANK_TRANSACTION_USER_ACCOUNT FOREIGN KEY (USERID)     
REFERENCES USER_ACCOUNT (USERID),
CONSTRAINT FK_BANK_TRANSACTION_BANK_ACCOUNT FOREIGN KEY (ACCOUNTID)     
REFERENCES BANK_ACCOUNT (ID)
);
GO